---
title: "Plagiotremus"
author:
  - Mykle L. Hoban:
      institute:
        - himb
      equal_contributor: yes
      correspondence: yes
      email: "mh@myklehoban.com"
  - Cameron A.J. Walsh:
      institute:
        - himb
      equal_contributor: yes
  - Randall K. Kosaki:
      institute: noaa
  - Brian W. Bowen:
      institute: himb
institute:
  - himb: Hawai&#x02BB;i Institute of Marine Biology
  - nerr: He&#x02BB;eia National Estuarine Research Reserve
  - natgeo: National Geographic Pristine Seas
  - noaa: National Oceanic and Atmospheric Administration
abstract:
  The Hawaiian archipelago is an endemism hotspot. Up to twenty-five percent of Hawaiian reef fish species are endemic, a higher proportion than anywhere else in the world (Randall 2007) However, unlike terrestrial species where high endemism often arises through adaptive radiation (e.g. honeycreepers (Freed et al. 1987), fruit flies (Carson 1983), silverswords (Witter and Carr 1988), etc.)—marine endemism in Hawai‘i is more evenly- distributed across taxa (Kay and Palumbi 1987; Mundy 2005).  Among reef fishes in Hawai‘i, sister taxa rarely co-occur, and when they do, they exhibit a higher degree of range size asymmetry than co-occurring sister species elsewhere in the Indo-Pacific (Gaboriau et al. 2018). In other words, the sister species of (small range size) Hawaiian endemics are typically widespread in the Indo-Pacific (large range size).
bibliography: references/citations.bib
csl: references/style.csl
output:
  word_document:
    pandoc_args:
      - "--toc-depth=2"
      - "--filter=resources/pandoc-crossref"
      - "--lua-filter=resources/scholarly-metadata.lua"
      - "--lua-filter=resources/author-info-blocks.lua"
      - "--reference-doc=resources/ref.docx"
    keep_md: true
tblPrefix: Table
figPrefix:
  - "figure"
  - "figures"
chapters: True
chaptersDepth: 1
chapDelim: ""
header-includes:
  - \usepackage{bm}
  - \usepackage{upgreek}

---

### Keywords {-}
<div custom-style="mono">ARMs, mesophotic coral ecosystems, community structure, dispersal, Hawai&#x02BB;i, brachyuran crabs</div>

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.path="output/figures/fig-",
  dev="svg",
  dpi=300,
  message=FALSE,
  warning=FALSE,
  cache=TRUE,
  cache.path = "cache/",
  cache.comments=FALSE
)
```

# Introduction {-}

Two examples of endemic Hawaiian reef fishes with widespread sister species are currently recognized within the fangtooth blenny genus Plagiotremus Gill, 1865 (Blennioidei: Blenniidae). Plagiotremus rhinorhynchos (Bleeker, 1852) and Plagiotremus tapeinosoma (Bleeker, 1857) are distributed across the tropical Indo-West-Pacific, from the Red Sea to the Marquesas. However, both species are replaced in Hawai‘i by their putative sister species Plagiotremus ewaensis [@brockNewBlennoidFish1948] and Plagiotremus goslinei [@strasburgNotesBlennioidFishes1956] respectively, both of which are endemic to the islands. When Smith-Vaniz [-@smith-vanizSabertoothedBlenniesTribe1976a] performed a phylogenetic analysis of Plagiotremus using 22 parsimony-informative morphological characters, he distinguished four “species groups” and three subgenera within Plagiotremus. The subgenus Plagiotremus, also known as the “spilistius species group” [@smith-vanizSabertoothedBlenniesTribe1976a], contains only Plagiotremus spilistius and Plagiotremus iosodon. This group originally included Plagiotremus celebesensis, however it was later merged with P. spilistius [@smith-vanizSabertoothedBlenniesTribe1987]. As the sister group to the subgenus Plagiotremus, Smith-Vaniz recognized the subgenus Musgravius containing the “laudandus species group” of Plagiotremus laudandus, Plagiotremus phenax, and Plagiotremus townsendi—although there has since been debate about whether the subspecies Plagiotremus laudandus flavus from Smith-Vaniz warrants species-level recognition [@hastingsRecognizingDiversityBlennioid2009a; @smith-vanizAggressiveMimicryAspidontus2020]. Finally, as the sister group to the two other subgenera, the subgenus Runula contains both the “rhinorhynchos species group” of P. rhinorhynchos and P. ewaensis, as well as the “tapeinosoma species group” comprised of P. tapeinosoma, P. goslinei, and Plagiotremus azaleus [@smith-vanizSabertoothedBlenniesTribe1976a]. Although Smith-Vaniz supported the Hawaiian endemic/widespread sister species relationships, he did not rule out the possibility that putative endemic species comprised isolated populations of their widespread sister species. Furthermore, he could not unambiguously resolve the interrelationships of subgenera within Plagiotremus, nor the placement of Plagiotremus relative to other genera in the tribe Nemophini. Although morphology-based phylogenetics has provided some taxonomic clarity within this group, molecular phylogenetics has the power to resolve many uncertain relationships.

Few species of Plagiotremus have been considered in molecular phylogenies. Plagiotremus rhinorhynchos and P. tapeinosoma have been included in several multilocus analyses of blennioids [@linPhylogenyBiogeographyShallow2013; @casewellEvolutionFangsVenom2017], while some have also included P. azaleus or P. laudandus as third species [@hundtMultilocusMolecularPhylogeny2014; @hundtExtremeDentitionDoes2018]. Most recently, Smith-Vaniz et al. [-@smith-vanizAggressiveMimicryAspidontus2020] compared cytochrome c oxidase subunit I (COI) gene sequences from five species of Plagiotremus (P. tapeinosoma, P. laudandus, P. flavus, P. townsendi, and P. phenax) using a neighbor-joining tree, calling for the reintegration of P. flavus as a subspecies under P. laudandus.

To resolve the taxonomy of Plagiotremus fishes at various levels, this study combined sequence data from hundreds of new Plagiotremus samples with sequences from a public database to create a molecular phylogeny. With data from nine putative Plagiotremus species and three other genera, this study presents the most taxonomically-comprehensive molecular phylogeny of Plagiotremus to-date. This allowed for comparisons with the morphology-based phylogeny at multiple levels. Furthermore, and of particular interest in Hawai‘i, this study is the first to present molecular sequence data from the endemic Hawaiian Plagiotremus species. If both P. ewaensis and P. goslinei are truly distinct from their widespread sister species P. rhinorhynchos and P. tapeinosoma, each should be considerably diverged from one another at the molecular level.

# Materials and Methods {-}

## Specimen collection {-}

We collected 360 samples of Plagiotremus spp. from Hawai‘i and abroad. Specimens were collected by pole spear and hand net and a portion of the caudal fin was preserved in a salt-saturated DMSO solution [@seutinPreservationAvianBlood2011] for subsequent DNA analysis. We collected 43 specimens of P. rhinorhynchos and 88 specimens of P. tapeinosoma across their ranges in the Indo-Pacific, from the Red sea to the Marquesas Islands. Additionally, we collected 42 P. ewaensis and 62 P. goslinei specimens from 13 different locations in the main (MHI) and northwest Hawaiian Islands (NWHI). All specimens from the Northwest Hawaiian Islands were collected under permits PMNM-2007-032, PMNM-2008-046, PMNM-2009-032L, PMNM-2009-044, PMNM-2011-025, and PMNM-2012-045, issued by the National Oceanic and Atmospheric Administration, the U.S. Fish and Wildlife Service, and the State of Hawaii Division of Aquatic Resources to BWB at the Hawai‘i Institute of Marine Biology. Fish sampling protocols were approved by the University of Hawai‘i at Manoa Institutional Animal Care & Use Committee under approval nos.. 09-753 and 15-2271.

## DNA extraction and sequencing {-}

Tissue samples were brought to the Hawai‘i Institute of Marine Biology (HIMB) for processing. We extracted genomic DNA using the EZNA-96 Tissue DNA Kit (Omega Bio-Tek, Norcross, GA, USA) following manufacturer’s protocols or a modified version of the HotSHOT protocol [@meekerMethodIsolationPCRready2007].  Specimens were amplified for a region of the mitochondrial cytochrome oxidase subunit I (COI) gene using the primers FishF1 (5’–TCAACCAACCACAAAGACATTGGCAC–3’) and FishR1 (5’–TAGACTTCTGGGTGGCCAAAGAATCA–3’) following the chemistry and thermocycler settings of Ward et al. [-@wardDNABarcodingAustralia2005]. Select specimens of Plagiotremus goslinei and P. tapeinosoma were also amplified for a region of cytochrome B (cytb) using the custom-designed forward primer BlnF3 (5’–TCAGTHTGATGAAACTTTGGCTC–3’) and the reverse primer cyb7 (5’–AATAGGAAGTATCATTCGGGTTTGAT–3’) [@taberletUnusualMitochondrialDNA1992]. PCR reactions for cytb were carried out in 15μl volumes consisting of 7.5μl BioMix Red™ (Bioline Inc., Massachusetts, USA), 0.3μl of each 10μM primer, 1.5μl BSA (New England Biolabs, Massachusetts, USA), 1μl DNA, and filled to volume with PCR-grade ultrapure water. Reactions were performed under the following conditions: 95°C for 2min followed by 35 cycles of denaturation at 94°C for 30s, annealing for 50°C for 45s, and extension at 72°C for 45s, with a final extension of 10min at 72°C. We visualized PCR products for all markers using 1.5-2% agarose gels stained with GelRed® Nucleic Acid Gel Stain (Biotium, California, USA) and purified final products by incubating with 0.75 units of exonuclease and 0.5 units of shrimp alkaline phosphatase (ExoSAP; USB, Ohio, USA) per PCR product for 30min at 37°C followed by 15min at 85°C. DNA sequencing was performed using fluorescently-labeled dideoxy terminators on an ABI 3730XL Genetic Analyzer (Applied Biosystems, California, USA) at the University of Hawai‘i Advanced Studies of Genomics, Proteomics and Bioinformatics sequencing facility.

## Additional sequence acquisition {-}

We downloaded all available COI sequence data in the Barcode of Life Database (BoLD) ascribed to the genera Plagiotremus, Xiphasia and Meiacanthus. Omobranchus has been identified and used as the outgroup to the tribe Nemophini in the multi-locus molecular phylogenies discussed above, so a COI sequence from Omobranchus anolius with identification and location information was downloaded from BoLD and used as the outgroup in our phylogenetic analyses. Three Plagiotremus sequences pulled from BoLD were excluded in downstream analyses due to unclear origins or mislabeling.
Maximum-likelihood phylogenetic tree estimation

## Sequence analysis {-}

Initial filtering was performed in the base environment of R 3.6.0 [@rcoreteamLanguageEnvironmentStatistical2019], a total of 327 COI sequences (234 de novo, 93 downloaded from BoLD) were used in phylogenetic tree estimation. Annotated R scripts used to perform all analyses in this paper can be found on GitHub (https://github.com) in the repository cajwalsh/plagio_project. The script used to perform the filtering described in this section is called “1_initial_filtering.R”.

Sequence data was loaded into R and interpreted using the packages “Biostrings” [@aboyounBiostringsEfficientManipulation2017] and “ape” [@paradisApeEnvironmentModern2019]. The sequences were aligned using the Clustal Omega algorithm [@sieversFastScalableGeneration2011] implemented in the R package “msa” [@bodenhoferMsaPackageMultiple2015]. Since the sequences analyzed here are from various sources, many have different lengths or include loci that are missing in the final alignment. To see how much various levels of missing data in the alignment affect the support of backbone nodes in a tree, three versions of the aligned dataset were used in tree estimation: one that excluded loci that were missing in more than one individual (hereafter referred to as the >99% coverage dataset), one that only included loci that were sequenced in >50% of individuals (>50% coverage dataset), and one in which all loci in the alignment were kept (the full dataset). Following filtering, identical sequences were merged to avoid overcrowding the tree and taxonomic as well as geographic spread of these shared sequences were recorded. The script used to perform this filtering in the cajwalsh/plagio_project repository is titled: “2_1_tree_alignment_filtering.R”.

Maximum likelihood phylogenetic tree estimation was performed with each of the three datasets using IQ-TREE 2 [@minhIQTREENewModels2020]. Within IQ-TREE 2, ModelFinder [@kalyaanamoorthyModelFinderFastModel2017] was used to determine the best substitution model prior to tree estimation, and 2000 ultrafast bootstraps (UFBoot) were performed using UFBoot2 [@hoangUFBoot2ImprovingUltrafast2018] following tree estimation. The authors of UFBoot2 suggest using a threshold of ≥95% support to trust a branch. All three of the resulting trees were interpreted and plotted in R using the packages “ape”, “treeio” [@wangTreeioPackagePhylogenetic2020], “ggplot2” [@wickhamGgplot2ElegantGraphics2009], “ggthemes” [@arnoldGgthemesExtraThemes2019], “ggtree” [@yuGgtreePackageVisualization2017], and “patchwork” [@pedersenPatchworkComposerPlots2020]. As a compromise between potential under- and over-filtering, the tree constructed using the >50% coverage dataset was used to examine the relationships within Plagiotremus. The script used to interpret and plot these trees in the cajwalsh/plagio_project repository is titled: “2_2_tree_plotting.R”.

## Haplotype network analysis {-}

Since the phylogenetic trees did not support reciprocal monophyly in P. tapeinosoma and P. goslinei, a haplotype network analysis was performed using all data from these two species as well as their closest relative P. azaleus. The sequences (149 original and 25 from BoLD) were interpreted and aligned using the same procedure and R packages as in the phylogenetic tree analysis. However, only loci sequenced in all samples were used in this analysis (i.e. no sites with missing data in any of the sequences were kept). Haplotype frequencies were calculated, arranged into a maximum-parsimony network [@templetonCladisticAnalysisPhenotypic1992], and plotted using a customized version of the R package “pegas” [@paradisPegasPackagePopulation2010]. Other aesthetic aspects were added to the network plot using “ggplot2” and “patchwork”, and a custom color palette was built using “RColorBrewer” [@neuwirthRColorBrewerColorBrewerPalettes2014] to display the location from which each sample originated. The locations were further grouped (by color) into the biogeographical regions previously defined for reef fishes by Kulbicki et al. [-@kulbickiGlobalBiogeographyReef2013]: P. azaleus is found in the Tropical Eastern Pacific realm, P. goslinei is restricted to the Hawaiian province (further split into the Northwestern Hawaiian Islands and Main Hawaiian Islands here) in the Indo-Pacific realm, while all other (P. tapeinosoma) samples came from various provinces in the Indo-Pacific realm.

# Results {-}

The alignment of all 327 COI sequences contained 698 base pairs. There was >99% coverage between base pairs 180 and 572 and >50% coverage between base pairs 106 and 634. The full dataset contained 184 unique haplotypes with 25 that were shared in at least two individuals (none were shared between species or between original and BoLD data sources), the >50% coverage dataset contained 158 unique haplotypes with 28 that were shared between at least two individuals (two shared between the different data sources), and the >99% coverage dataset contained 123 unique haplotypes with 33 that were shared between at least two individuals (nine of which were shared between original and BoLD data sources while five were shared between species). There were 249 parsimony-informative sites in the full dataset, 194 in the >50% coverage dataset, and 149 in the >99% coverage dataset. ModelFinder selected the TPM2+F+G4 substitution model as the best fit for all three datasets.

Trees built using all three datasets showed ≥94% support for the monophyly of both Xiphasia and Meiacanthus, with lower support (72–94%) for the monophyly of Plagiotremus (Figure 1). Each of the three trees also placed two Meiacanthus grammistes sequences (Mgr-502 & Mgr-504) in a clade distinct from the rest of Meiacanthus (including other individuals from their own species) as more closely related to Plagiotremus. Although there was generally low support for inter-genus relationships in all trees, both the full and >50% coverage trees considered Meiacanthus as the sister genus to Plagiotremus (plus Mgr-502 & 504) while the >99% coverage tree placed Xiphasia as sister genus to Plagiotremus (plus Mgr-502 & 504).

Almost all species within Plagiotremus were resolved as monophyletic with high (≥94% UFBoot) support (Figure 2). All P. rhinorhynchos and P. ewaensis samples were arranged in a well-supported sister group to all other Plagiotremus species. Reciprocal monophyly of these two species was also well supported (with the exception of Prh-022—one of many original samples from Diego Garcia in the Chagos Archipelago). One division of the other well-supported Plagiotremus clade contained P. townsendi, P. phenax, P. laudandus, and P. flavus. The first two of these four species made up their own well-supported clade which was sister to one containing the latter two (as P. flavus has historically been considered a subspecies of P. laudandus). The last remaining inter-species node with high support contains P. azaleus, P. tapeinosoma, and P. goslinei. Within this group, P. azaleus is separated from P. tapeinosoma and P. goslinei with low (45%) support, and the latter two species form a mixed clade. Other tree iterations nested both P. azaleus amongst mixed P. tapeinosoma and P. goslinei clades (although P. azaleus itself was always monophyletic and highly-diverged). This mixed clade with relatively low support was analyzed further in the haplotype network analysis.

Post-alignment filtering for the haplotype network analysis of P. azaleus, P. tapeinosoma, and P. goslinei yielded a contiguous sequence of 466 bp (between 107 and 572) of the original 698 bp alignment. Three main haplotypes were apparent in the network, each being shared by 45, 36, and 20 individuals. No other haplotypes were shared by more than four individuals. The two most common haplotypes were shared by P. tapeinosoma and P. goslinei. Thirty-nine P. goslinei (in Hawai‘i) and six P. tapeinosoma (five from the Central Pacific province and one from the Polynesian province) shared the most common haplotype. The second most common haplotype was shared by 36 individuals, one of which was from the NW Hawaiian Islands (i.e. P. goslinei), while the remaining 35 (P. tapeinosoma) were from almost all other provinces in the Indo-Pacific realm ranging from South Africa and the Red Sea in the western Indian Ocean to the Society Islands in Polynesia. These two most common haplotypes (one of which is shared by the majority of P. goslinei and one of which is the most common amongst P. tapeinsoma) only differ by one nucleotide (at position 96 of the 466 base pair sequence). A third haplotype shared by one P. tapeinosoma and one P. goslinei is different from the main Hawaiian haplotype at a single nucleotide position. Two P. goslinei individuals shared a haplotype that was more closely related to the main P. tapeinosoma than it was to most P. goslinei haplotypes, and two P. tapeinosoma from the Central Pacific had haplotypes that were more closely-related to the main P. goslinei haplotype. Most of the remaining (less frequent) P. tapeinosoma and P. goslinei haplotypes were not more than a few nucleotides different from either of the two most common haplotypes. The exception to this is the third most common haplotype to which all P. tapeinosoma from the Marquesas (in the easternmost point of the Polynesian province) either shared or were linked to. This third most common haplotype was distinct from the main P. tapeinosoma haplotype at seven nucleotide positions (~1.5%). All samples from the Marquesas differed by between six and ten nucleotides (1.2–2.1%) from the main P. tapeinosoma haplotype. The two P. azaleus samples were considerably diverged (a minimum of 43 steps or 9.2%) from the closest P. tapeinosoma haplotype.

# Discussion {-}

This study of COI gene sequences from 327 Nemophini fishes supported the monophyly of most genera and species considered. Meiacanthus was identified as the sister genus to Plagiotremus, with Xiphasia as the sister to this two-genus group. Almost all species within Plagiotremus exhibited well-supported reciprocal monophyly with the exception being the group containing P. azaleus, P. tapeinosoma, and P. goslinei. Within this group, P. azaleus is very clearly diverged while P. tapeinosoma from the Marqueseas are more distinct from the rest of P. tapeinosoma than P. goslinei is as these latter two groups share several haplotypes.

Only one previously-published phylogeny has supported Meiacanthus as the sister genus to Plagiotremus [@linPhylogenyBiogeographyShallow2013]. All subsequent phylogenies found Xiphasia to be the sister genus of Plagiotremus while the position of Meiacanthus within Nemophini has varied [@hundtMultilocusMolecularPhylogeny2014; @casewellEvolutionFangsVenom2017; @hundtExtremeDentitionDoes2018]. These later differences have been attributed by some authors to be due to increased taxonomic coverage within Meiacanthus and other Nemophini genera [@hundtMultilocusMolecularPhylogeny2014]. While this COI phylogeny is limited by a lack of genetic resolution, it is plausible that the increased taxonomic resolution of this study led to the inference of different relationships. Relative to the previous multi-locus phylogenies, this study considered three times more Plagiotremus species and included considerable geographic variation by analyzing individuals from as many locations as possible across all genera and species. However, interpretation of the genus-level relationships observed here should only be considered speculative as they were not well supported overall. Increasing both the genetic and taxonomic resolution in future phylogenetic studies may further resolve these relationships.

In attempting to resolve the phylogenetic relationships between the “species groups” he defined within Plagiotremus, Smith-Vaniz [@smith-vanizSabertoothedBlenniesTribe1976a] noted that:

“Rigid application of the principles of phylogenetic (cladistic) systematics dictates that the laudandus and tapeinosoma species groups be accorded a sister-group relationship because they share the greatest number of apomorphic characters…However…I believe their occurrence in both groups is a case of parallel evolution.”

The results of this genetic study, however, support the “rigid cladistic” interpretation. The clearest divergence within Plagiotremus was between the “rhinorhynchos species group” and all others. Long internal branches separated these well-supported groups. This topology indicates that the previously-recognized subgenus Runula is polyphyletic as its constituent “tapeinosoma species group” is in fact more closely related to the “laudandus species group” (subgenus Musgravius) than to the “rhinorhynchos species group” that was also placed in Runula by Smith-Vaniz [-@smith-vanizSabertoothedBlenniesTribe1976a]. Other molecular phylogenies also support this alternative arrangement of “species groups” within Plagiotremus. Similar to this study, Hundt et al. [-@hundtMultilocusMolecularPhylogeny2014] found P. tapeinsoma to be more closely-related to P. laudandus than P. rhinorhynchos (although these were the only three Plagiotremus species considered in this study), and all phylogenetic analyses that have included P. rhinorhynchos put it on a rather long branch relative to other species within Nemophini [@linPhylogenyBiogeographyShallow2013; @hundtMultilocusMolecularPhylogeny2014; @hundtExtremeDentitionDoes2018]. These results suggest that the subgenus Runula should be dissolved. Further analyses including samples from the “spilistius species group” not considered here would provide a more complete picture of the relationships of all Plagiotremus species.

Both Hawaiian endemic species within Plagiotremus were considered by Smith-Vaniz to potentially only warrant subspecies recognition. The reciprocal monophyly of the Hawaiian endemic P. ewaensis and the widespread P. rhinorhynchos in this study validates the species-level status of the former. While Smith-Vaniz distinguished P. ewaensis and P. rhinorhynchos based on their color patterns and significantly different number of incisors, he more generally based his decision to uphold species-level recognition for both Hawaiian endemics based on the precedent set by Gosline and Brock [-@goslineHandbookHawaiianFishes1960]—the first of whom was honored by the naming of P. goslinei, and the second of whom initially described P. ewaensis. The arguments of Gosline and Brock were that: (1) there was no biological reason not to recognize the Hawaiian endemics as full species as there was no “intergradation” between them and their widespread relatives (i.e. intermediate or mixed forms), and (2) they were the most distinctive sub-groups in the Indo-West-Pacific. In light of the results of this study, the arguments of Gosline and Brock no longer hold for P. goslinei.

Regarding the first argument concerning intergradation, P. goslinei and P. tapeinosoma share multiple haplotypes. In more recent discussion of (full) species delimitation (i.e. in the era of molecular phylogenies) Smith-Vaniz et al. [@smith-vanizAggressiveMimicryAspidontus2020] argue (regarding P. laudandus/flavus) that:

“Shared haplotypes are characteristic of populations making up a single species but are not proof two populations are the same species. The exception would be when phenotypes are consistently different and the boundaries well-defined; in that case two populations sharing haplotypes may represent recently split species and/or established species with some low degree of hybridization”.

While shared haplotypes between P. goslinei and P. tapeinosoma alone may not be sufficient to synonymize them (as they may still be diverging if truly isolated), the fact that two P. goslinei samples were more closely-related to P. tapeinosoma and two P. tapeinsoma samples from Kiribati and Palau were more closely-related to the main P. goslinei haplotype is evidence of recent migration between the two groups with supposedly different ranges. This potential recent mixing along with the presence of shared haplotypes imply that they are not demographically or evolutionarily distinct (yet, at least).

Regarding the second argument of Hawaiian endemics being the most distinct in the Indo-West-Pacific, P. tapeinosoma from the Marquesas is considerably more diverged from the rest of P. tapeinosoma than P. goslinei is, despite not also being considered a distinct species. Smith-Vaniz [@smith-vanizSabertoothedBlenniesTribe1976a] recognized that Marquesan P. tapeinosoma had meristic values (fish trait counts/measurements) “at least as low as those of goslinei” that potentially warranted them subspecies status. Therefore, according to the criteria specified by previous authors to justify their own species-level taxonomic recognition of Hawaiian endemics [@goslineHandbookHawaiianFishes1960; @smith-vanizSabertoothedBlenniesTribe1976a], P. goslinei should likely not be considered a distinct species from P. tapeinosoma. On the other hand, P. tapeinosoma samples on literal opposite sides of the planet shared the same COI haplotype while P. goslinei is almost completely diverged from the rest of the “tapeinosoma species group”. Therefore, joint study of how phenotypic and genetic variation is partitioned geographically within the geographic “tapeinosoma species group” lineages (wider Indo-Pacific, Hawaiian, Marquesas, and Eastern Pacific) should be carried out to clarify their interrelationships and taxonomic statuses. This would likely result in P. tapeinosoma from the Marquesas being formally described as a distinct species given its complete genetic divergence from P. tapeinosoma outside of Polynesia and its meristic distinctness observed by Smith-Vaniz [-@smith-vanizSabertoothedBlenniesTribe1976a].

Although P. azaleus (in the Eastern Pacific) is considerably diverged from all other “tapeinosoma species group” lineages, the initial description of P. goslinei [@strasburgNotesBlennioidFishes1956] suggested that it may be a geographical intermediate of P. azaleus and P. tapeinosoma. The placement of P. azaleus as the sister group to P. tapeinosoma and P. goslinei in this study was not well supported, and other trees nested it within mixed groups of P. tapeinosoma and P. goslinei. Furthermore, although P. azaleus was closest to a P. tapeinosoma haplotype in the network, only one to two more steps separated it from multiple P. goslinei clusters—which is very few relative to its 43 steps from the rest of the network. Therefore, further genetic study of these lineages could determine whether P. azaleus originally colonized the Eastern Pacific through Hawai‘i (sharing an ancestor with P. goslinei there as well) and contribute to the growing literature about whether isolated islands with high levels of endemism export biodiversity to other regions [@bowenOriginsTropicalMarine2013]. On the other hand, both the P. azaleus and Marquesan P. tapeinosoma haplotypes were linked to the rest of P. tapeinosoma through Indian Ocean haplotypes (rather than those from the Pacific which are much closer). This may indicate that the divergence of these lineages dates back to the closure of the Tethys Sea (that divided the tropical Atlantic and Indo-Pacific realms) as observed in many other reef fish groups [@floeterAtlanticReefFish2008].

The taxonomy and phylogeography of fangblennies was elucidated in this study by including more species than ever before in a molecular phylogeny of Plagiotremus. Although only one of the Hawaiian lineages seems to merit full species status, further study of the phenotypic and genetic variation within the “tapeinosoma” sub-group could lead to the description of distinct species in other regions, as well as provide further insight into how endemic marine species evolve in some of the world’s most isolated archipelagos.

# References {-}

::: {#refs}
:::

# Supplemental material {label="S"}

